version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-runner}
      args:
        NODE_ENV: ${NODE_ENV:-production}
        NEXT_PUBLIC_API_URL_BACKEND: ${NEXT_PUBLIC_API_URL_BACKEND}
        NEXT_PUBLIC_N8N_CHAT: ${NEXT_PUBLIC_N8N_CHAT}
    ports:
      - '${PORT:-3000}:3000'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-3000}
      - NEXT_PUBLIC_API_URL_BACKEND=${NEXT_PUBLIC_API_URL_BACKEND}
      - NEXT_PUBLIC_N8N_CHAT=${NEXT_PUBLIC_N8N_CHAT}
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
